# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import azure_cognitive_services_speech_sdk_swagger_client
from azure_cognitive_services_speech_sdk_swagger_client.models.paginated_projects import (
    PaginatedProjects,
)  # noqa: E501
from azure_cognitive_services_speech_sdk_swagger_client.rest import ApiException


class TestPaginatedProjects(unittest.TestCase):
    """PaginatedProjects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedProjects(self):
        """Test PaginatedProjects"""
        # FIXME: construct object with mandatory attributes with example values
        # model = azure_cognitive_services_speech_sdk_swagger_client.models.paginated_projects.PaginatedProjects()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
