# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import azure_cognitive_services_speech_sdk_swagger_client
from azure_cognitive_services_speech_sdk_swagger_client.models.body import (
    Body,
)  # noqa: E501
from azure_cognitive_services_speech_sdk_swagger_client.rest import ApiException


class TestBody(unittest.TestCase):
    """Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody(self):
        """Test Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = azure_cognitive_services_speech_sdk_swagger_client.models.body.Body()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
