# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import azure_cognitive_services_speech_sdk_swagger_client
from azure_cognitive_services_speech_sdk_swagger_client.models.evaluations_locales_get200_application_json_response import (
    EvaluationsLocalesGet200ApplicationJsonResponse,
)  # noqa: E501
from azure_cognitive_services_speech_sdk_swagger_client.rest import ApiException


class TestEvaluationsLocalesGet200ApplicationJsonResponse(unittest.TestCase):
    """EvaluationsLocalesGet200ApplicationJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvaluationsLocalesGet200ApplicationJsonResponse(self):
        """Test EvaluationsLocalesGet200ApplicationJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = azure_cognitive_services_speech_sdk_swagger_client.models.evaluations_locales_get200_application_json_response.EvaluationsLocalesGet200ApplicationJsonResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
