# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import azure_cognitive_services_speech_sdk_swagger_client
from azure_cognitive_services_speech_sdk_swagger_client.api.default_api import (
    DefaultApi,
)  # noqa: E501
from azure_cognitive_services_speech_sdk_swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = (
            azure_cognitive_services_speech_sdk_swagger_client.api.default_api.DefaultApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_datasets_commit_blocks(self):
        """Test case for datasets_commit_blocks

        Commit Block List  # noqa: E501
        """
        pass

    def test_datasets_create(self):
        """Test case for datasets_create

        Create Dataset  # noqa: E501
        """
        pass

    def test_datasets_delete(self):
        """Test case for datasets_delete

        Delete Dataset  # noqa: E501
        """
        pass

    def test_datasets_get(self):
        """Test case for datasets_get

        Get Dataset  # noqa: E501
        """
        pass

    def test_datasets_get_blocks(self):
        """Test case for datasets_get_blocks

        Get Uploaded Blocks  # noqa: E501
        """
        pass

    def test_datasets_get_file(self):
        """Test case for datasets_get_file

        Get Dataset File  # noqa: E501
        """
        pass

    def test_datasets_list(self):
        """Test case for datasets_list

        Get Datasets  # noqa: E501
        """
        pass

    def test_datasets_list_files(self):
        """Test case for datasets_list_files

        Get Dataset Files  # noqa: E501
        """
        pass

    def test_datasets_list_supported_locales(self):
        """Test case for datasets_list_supported_locales

        Get Supported Locales for Datasets  # noqa: E501
        """
        pass

    def test_datasets_update(self):
        """Test case for datasets_update

        Update Dataset  # noqa: E501
        """
        pass

    def test_datasets_upload(self):
        """Test case for datasets_upload

        Upload Dataset From Form  # noqa: E501
        """
        pass

    def test_datasets_upload_block(self):
        """Test case for datasets_upload_block

        Upload Data Block  # noqa: E501
        """
        pass

    def test_endpoints_create(self):
        """Test case for endpoints_create

        Create Endpoint  # noqa: E501
        """
        pass

    def test_endpoints_delete(self):
        """Test case for endpoints_delete

        Delete Endpoint  # noqa: E501
        """
        pass

    def test_endpoints_delete_base_model_log(self):
        """Test case for endpoints_delete_base_model_log

        Delete Base Model Endpoint Log  # noqa: E501
        """
        pass

    def test_endpoints_delete_base_model_logs(self):
        """Test case for endpoints_delete_base_model_logs

        Delete All Base Model Endpoint Logs  # noqa: E501
        """
        pass

    def test_endpoints_delete_log(self):
        """Test case for endpoints_delete_log

        Delete Custom Model Endpoint Log  # noqa: E501
        """
        pass

    def test_endpoints_delete_logs(self):
        """Test case for endpoints_delete_logs

        Delete All Custom Model Endpoint Logs  # noqa: E501
        """
        pass

    def test_endpoints_get(self):
        """Test case for endpoints_get

        Get Endpoint  # noqa: E501
        """
        pass

    def test_endpoints_get_base_model_log(self):
        """Test case for endpoints_get_base_model_log

        Get Base Model Endpoint Log  # noqa: E501
        """
        pass

    def test_endpoints_get_log(self):
        """Test case for endpoints_get_log

        Get Custom Model Endpoint Log  # noqa: E501
        """
        pass

    def test_endpoints_list(self):
        """Test case for endpoints_list

        Get Endpoints  # noqa: E501
        """
        pass

    def test_endpoints_list_base_model_logs(self):
        """Test case for endpoints_list_base_model_logs

        Get Base Model Logs  # noqa: E501
        """
        pass

    def test_endpoints_list_logs(self):
        """Test case for endpoints_list_logs

        Get Endpoint Logs  # noqa: E501
        """
        pass

    def test_endpoints_list_supported_locales(self):
        """Test case for endpoints_list_supported_locales

        Get Supported Locales for Endpoints  # noqa: E501
        """
        pass

    def test_endpoints_update(self):
        """Test case for endpoints_update

        Update Endpoint  # noqa: E501
        """
        pass

    def test_evaluations_create(self):
        """Test case for evaluations_create

        Create Evaluation  # noqa: E501
        """
        pass

    def test_evaluations_delete(self):
        """Test case for evaluations_delete

        Delete Evaluation  # noqa: E501
        """
        pass

    def test_evaluations_get(self):
        """Test case for evaluations_get

        Get Evaluation  # noqa: E501
        """
        pass

    def test_evaluations_get_file(self):
        """Test case for evaluations_get_file

        Get Evaluation File  # noqa: E501
        """
        pass

    def test_evaluations_list(self):
        """Test case for evaluations_list

        Get Evaluations  # noqa: E501
        """
        pass

    def test_evaluations_list_files(self):
        """Test case for evaluations_list_files

        Get Evaluation Files  # noqa: E501
        """
        pass

    def test_evaluations_list_supported_locales(self):
        """Test case for evaluations_list_supported_locales

        Get Supported Locales for Evaluations  # noqa: E501
        """
        pass

    def test_evaluations_update(self):
        """Test case for evaluations_update

        Update Evaluation  # noqa: E501
        """
        pass

    def test_health_status_get(self):
        """Test case for health_status_get

        Get Health Status  # noqa: E501
        """
        pass

    def test_models_copy_to(self):
        """Test case for models_copy_to

        Copy Model  # noqa: E501
        """
        pass

    def test_models_create(self):
        """Test case for models_create

        Create Model  # noqa: E501
        """
        pass

    def test_models_delete(self):
        """Test case for models_delete

        Delete Model  # noqa: E501
        """
        pass

    def test_models_get_base_model(self):
        """Test case for models_get_base_model

        Get Base Model  # noqa: E501
        """
        pass

    def test_models_get_base_model_manifest(self):
        """Test case for models_get_base_model_manifest

        Get Base Model Manifest  # noqa: E501
        """
        pass

    def test_models_get_custom_model(self):
        """Test case for models_get_custom_model

        Get Model  # noqa: E501
        """
        pass

    def test_models_get_custom_model_manifest(self):
        """Test case for models_get_custom_model_manifest

        Get Model Manifest  # noqa: E501
        """
        pass

    def test_models_get_file(self):
        """Test case for models_get_file

        Get Model File  # noqa: E501
        """
        pass

    def test_models_list_base_models(self):
        """Test case for models_list_base_models

        Get Base Models  # noqa: E501
        """
        pass

    def test_models_list_custom_models(self):
        """Test case for models_list_custom_models

        Get Models  # noqa: E501
        """
        pass

    def test_models_list_files(self):
        """Test case for models_list_files

        Get Model Files  # noqa: E501
        """
        pass

    def test_models_list_supported_locales(self):
        """Test case for models_list_supported_locales

        Get Supported Locales for Models  # noqa: E501
        """
        pass

    def test_models_update(self):
        """Test case for models_update

        Update Model  # noqa: E501
        """
        pass

    def test_projects_create(self):
        """Test case for projects_create

        Create Project  # noqa: E501
        """
        pass

    def test_projects_delete(self):
        """Test case for projects_delete

        Delete Project  # noqa: E501
        """
        pass

    def test_projects_get(self):
        """Test case for projects_get

        Get Project  # noqa: E501
        """
        pass

    def test_projects_list(self):
        """Test case for projects_list

        Get Projects  # noqa: E501
        """
        pass

    def test_projects_list_datasets(self):
        """Test case for projects_list_datasets

        Get Datasets for Project  # noqa: E501
        """
        pass

    def test_projects_list_endpoints(self):
        """Test case for projects_list_endpoints

        Get Endpoints for Project  # noqa: E501
        """
        pass

    def test_projects_list_evaluations(self):
        """Test case for projects_list_evaluations

        Get Evaluations for Project  # noqa: E501
        """
        pass

    def test_projects_list_models(self):
        """Test case for projects_list_models

        Get Models for Project  # noqa: E501
        """
        pass

    def test_projects_list_supported_locales(self):
        """Test case for projects_list_supported_locales

        Get Supported Locales for Projects  # noqa: E501
        """
        pass

    def test_projects_list_transcriptions(self):
        """Test case for projects_list_transcriptions

        Get Transcriptions for Project  # noqa: E501
        """
        pass

    def test_projects_update(self):
        """Test case for projects_update

        Update Project  # noqa: E501
        """
        pass

    def test_transcriptions_create(self):
        """Test case for transcriptions_create

        Create Transcription  # noqa: E501
        """
        pass

    def test_transcriptions_delete(self):
        """Test case for transcriptions_delete

        Delete Transcription  # noqa: E501
        """
        pass

    def test_transcriptions_get(self):
        """Test case for transcriptions_get

        Get Transcription  # noqa: E501
        """
        pass

    def test_transcriptions_get_file(self):
        """Test case for transcriptions_get_file

        Get Transcription File  # noqa: E501
        """
        pass

    def test_transcriptions_list(self):
        """Test case for transcriptions_list

        Get Transcriptions  # noqa: E501
        """
        pass

    def test_transcriptions_list_files(self):
        """Test case for transcriptions_list_files

        Get Transcription Files  # noqa: E501
        """
        pass

    def test_transcriptions_list_supported_locales(self):
        """Test case for transcriptions_list_supported_locales

        Get Supported Locales for Transcriptions  # noqa: E501
        """
        pass

    def test_transcriptions_update(self):
        """Test case for transcriptions_update

        Update Transcription  # noqa: E501
        """
        pass

    def test_web_hooks_create(self):
        """Test case for web_hooks_create

        Create Web Hook  # noqa: E501
        """
        pass

    def test_web_hooks_delete(self):
        """Test case for web_hooks_delete

        Delete Web Hook  # noqa: E501
        """
        pass

    def test_web_hooks_get(self):
        """Test case for web_hooks_get

        Get Web Hook  # noqa: E501
        """
        pass

    def test_web_hooks_list(self):
        """Test case for web_hooks_list

        Get Web Hooks  # noqa: E501
        """
        pass

    def test_web_hooks_ping(self):
        """Test case for web_hooks_ping

        Ping Web Hook  # noqa: E501
        """
        pass

    def test_web_hooks_test(self):
        """Test case for web_hooks_test

        Test Web Hook  # noqa: E501
        """
        pass

    def test_web_hooks_update(self):
        """Test case for web_hooks_update

        Update Web Hook  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
