from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from azure_cognitive_services_speech_sdk_swagger_client.api.custom_speech_datasets_for_model_adaptation_api import CustomSpeechDatasetsForModelAdaptationApi
from azure_cognitive_services_speech_sdk_swagger_client.api.custom_speech_endpoints_api import CustomSpeechEndpointsApi
from azure_cognitive_services_speech_sdk_swagger_client.api.custom_speech_model_evaluations_api import CustomSpeechModelEvaluationsApi
from azure_cognitive_services_speech_sdk_swagger_client.api.custom_speech_models_api import CustomSpeechModelsApi
from azure_cognitive_services_speech_sdk_swagger_client.api.custom_speech_projects_api import CustomSpeechProjectsApi
from azure_cognitive_services_speech_sdk_swagger_client.api.custom_speech_transcriptions_api import CustomSpeechTranscriptionsApi
from azure_cognitive_services_speech_sdk_swagger_client.api.custom_speech_web_hooks_api import CustomSpeechWebHooksApi
from azure_cognitive_services_speech_sdk_swagger_client.api.service_health_api import ServiceHealthApi
